spring:
  kafka:
    bootstrap-servers: 10.2.10.41:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-offset-reset: earliest
      auto-commit-interval: 1000

